services:
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    restart: always
    environment:
      MONGO_INITDB_DATABASE: chats
      MONGO_INITDB_ROOT_USERNAME: chats-admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    volumes:
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
